spring.application.name=ChatApp

spring.data.mongodb.uri=mongodb+srv://chatuser:chatpass123@chatapp.aksfc52.mongodb.net/chatapp?tls=true&retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000


